---
- minikube_dependencies:
    - unzip

- name: install docker minikube
  hosts: localhost
  become: yes
  become_user: vagrant
  vars: 
    minikube_install_dir: /usr/local/bin/kube
    minikube_version: latest
    kubectl_version: v1.9.1
    docker_machine_version: v0.13.0
    terraform_version: 0.12.24

 


  tasks:
    - name: set facts
      set_fact:
        translated_architecture: amd64
      when: ansible_architecture == 'x86_64' 


    - name: Create a directory if it does not exist
      file:
       path: /usr/local/bin/kube
       state: directory
       
      become: yes
      become_user: root
        # - name: install kubectl 
   #   become_method: sudo
   #   get_url: url="curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl" des="/home/vagrant/kube"
      #shell: chmod +x ./kubectl 
      #shell: mv ./kubectl /usr/local/bin/kubectl


    - name: get binaries
      get_url: url="{{ item.url }}" dest="{{ item.dest }}"
      with_items:
        - url: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-{{ ansible_system|lower }}-amd64
          dest: "{{ minikube_install_dir }}/minikube"
        - url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/{{ ansible_system|lower }}/{{ translated_architecture }}/kubectl"
          dest: "{{ minikube_install_dir }}/kubectl"
        - url: "https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine-{{ ansible_system }}-{{ ansible_architecture }}"
          dest: "{{ minikube_install_dir }}/docker-machine"
        - url: "https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_{{ ansible_system }}_{{ ansible_architecture }}.zip"
          dest: "{{ minikube_install_dir }}/terrafrom"
      become: yes 
      become_user: root


    - name: install the required packages
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ minikube_dependencies }}"

    - name: chmod binaries
      file: dest="{{ minikube_install_dir }}/{{ item }}" mode=0755
      with_items:
        - minikube
        - kubectl
        - docker-machine
      become: yes
      become_user: root
 
    - name: start minikube 
      become: yes 
      become_user: root 
      shell: minikube start --vm-driver=none 
      
      
    - name: unzip terraform  
      shell: unzip {{ minikube_install_dir }}/terrafrom/terraform_{{terraform_version}}_{{ ansible_system }}_{{ ansible_architecture }}.zip
      
    - name: copy to bin root
      shell: mv {{ minikube_install_dir }}/terrafrom/terraform /usr/local/bin
    - name: create dir  
      file:
       path: /terraform
       state: directory
       
    - name: copy terraform file 
      src: /home/vagrant/dev-terra-ani-vag/main.tf
      dest: /terraform/

    - name: execute terraform init 
      shell: terraform init
      
    - name: terraform plan 
      shell: terraform plan 
      
    - name: terraform apply 
      shell: terraform apply 

      
    
      
