---


- name: install docker minikube
  hosts: localhost
  become: yes
  become_user: vagrant
  vars: 
    minikube_install_dir: /usr/local/bin
    minikube_version: latest
    kubectl_version: v1.9.1
    docker_machine_version: v0.16.2
    terraform_version: 0.12.24
   
    
 


  tasks:
    - name: set facts
      set_fact:
        translated_architecture: amd64
      when: ansible_architecture == 'x86_64' 


    - name: Create a directory if it does not exist
      file:
       path: /usr/local/bin/
       state: directory
       
      become: yes
      become_user: root
        # - name: install kubectl 
   #   become_method: sudo
   #   get_url: url="curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl" des="/home/vagrant/kube"
      #shell: chmod +x ./kubectl 
      #shell: mv ./kubectl /usr/local/bin/kubectl


    - name: get binaries
      get_url: url="{{ item.url }}" dest="{{ item.dest }}"
      with_items:
        - url: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-{{ ansible_system|lower }}-amd64
          dest: "/usr/local/bin/minikube"
        - url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/{{ ansible_system|lower }}/{{ translated_architecture }}/kubectl"
          dest: "{{ minikube_install_dir }}/kubectl"
        - url: "https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine-{{ ansible_system }}-{{ ansible_architecture }}"
          dest: "{{ minikube_install_dir }}/docker-machine"
        - url: "https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_linux_amd64.zip"
          dest: "{{ minikube_install_dir }}/terrafrom"
      become: yes 
      become_user: root


    - name: install the required packages
      shell: apt install unzip -y
      become: yes
      become_user: root

    - name: install docker 
      shell: apt install docker -y 
      become: yes
      become_user: root


    - name: chmod binaries
      file: dest="{{ minikube_install_dir }}/{{ item }}" mode=0755
      with_items:
        
        - kubectl
        - docker-machine
      become: yes
      become_user: root
 
    - name: chmod minikube
      file: dest="/usr/local/bin/minikube" mode=0755
      become: yes
      become_user: root

#    - name: start minikube 
#      become: yes 
#      become_user: root 
#      shell: minikube start --vm-driver=docker 
      
      
#    - name: unzip terraform  
#      shell: unzip {{ minikube_install_dir }}/terrafrom/terraform_{{terraform_version}}_{{ ansible_system }}_{{ ansible_architecture }}.zip
      
#    - name: copy to bin root
#      shell: mv {{ minikube_install_dir }}/terraform /usr/local/bin
#    - name: create dir  
#      file:
#       path: /terraform
#       state: directory
       
#    - name: copy terraform file 
#      shell: cp /dev-terra-ani-vag/main.tf /terraform/main.tf
##      src: /dev-terra-ani-vag/main.tf
##      dest: /terraform/main.tf

#    - name: execute terraform init 
#      shell: terraform init
      
#    - name: terraform plan 
#      shell: terraform plan 
      
#    - name: terraform apply 
#      shell: terraform apply 

      
    
      
